In [1]:
matrix = [[j for j in range(i,i+3)] for i in range(1,8,3)]
matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [2]:
import numpy as np

In [3]:
array1 = np.array([10, 100, 1000.])

In [4]:
array2 = np.array([[1., 2., 3.],
                   [4., 5., 6.]])

由于数组中有一个是浮点数，根据NumPy对同构的要求，全部的数据类型都是float64类型

In [5]:
array1.dtype

dtype('float64')

NumPy的向量化：标量和NumPy数组求和，NumPy会执行按元素的操作，省去了数组遍历的过程

标量指的是某种Python基本数据类型

In [6]:
array1 + 1

array([  11.,  101., 1001.])

In [7]:
array2 + 2

array([[3., 4., 5.],
       [6., 7., 8.]])

两个数组的计算也是按元素来运算

In [8]:
array2 * array2

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

NumPy的广播：使用两个形状不同的数组运算，NumPy会自动将形状较小的数组广播到与另一个数组兼容的形状

In [9]:
array2 * array1  # 和array1 * array2的结果相同

array([[  10.,  200., 3000.],
       [  40.,  500., 6000.]])

通用函数（ufunc）：NumPy的函数库，提供了大量的数学函数，这些函数对数组中的每个元素进行操作

In [10]:
"""
不能使用python标准库中的math模块来算平方根，因为math.sqrt只能对单个标量进行操作。
使用NumPy的通用函数，可以对多维数组进行操作
"""
import math
math.sqrt(array1)

TypeError: only size-1 arrays can be converted to Python scalars

In [ ]:
np.array([[math.sqrt(i) for i in row] for row in array2])

In [ ]:
np.sqrt(array2)

In [ ]:
array2.sum(axis=0)

array([5., 7., 9.])

In [ ]:
array2.sum(axis=1)

array([ 6., 15.])

In [ ]:
array2[:, 1:]

array([[2., 3.],
       [5., 6.]])

———————————————————————————————————————

- arange()和range()类似，可以快速创建数组。arange()可以指定起始值、终止值和步长，步长默认为1
- reshape()可以改变数组的形状，参数为新的形状

In [ ]:
arr3 = np.arange(1,13).reshape(3, 4)
arr3

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

除了arange()，还可以使用np.ones和np.zeros来创建全1或者全0的数组。np.eye可以创建单位矩阵。（括号中是矩阵的形状）

In [ ]:
arr4 = np.ones((3, 4))
arr4

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
arr5 = np.eye(4)
arr5

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])